### ISSUE TITLE
Problem requiring npm packages that themselves require npm packages

### ISSUE THREAD

**Issue by johnnyreilly** [substack/webworkify#14]
Hi,

First of all, thanks for Browserify - I **love** it!  

I've recently been turning my attention to web workers and I've experienced some teething problems using webworkify.  The example has you requiring [gamma](https://www.npmjs.com/package/gamma) and using it successfully. However, I've had problems with module resolution when I try and require / import [protobufjs](https://www.npmjs.com/package/protobufjs).

The workaround seems to be switching from 

`var ProtoBuf = require("protobufjs");`

to 

`var ProtoBuf = require("../../node_modules/protobufjs");`

I note that the `main` for gamma is the `index.js` in the root of the package.   In the case of ProtobufJS there's an `index.js` in the root which requires "dist/ProtoBuf.js".  Also,  in the `main` the package points to "dist/ProtoBuf.js".  

It looks like there might be an issue with webworkify being used to require packages that themselves require other packages.

**Comment by mourner** [comment]
Hey, do you think this issue is still relevant? I haven't been able to reproduce this, and webworkify works fine with a very complicated dependency tree in projects like https://github.com/mapbox/mapbox-gl-js. Please let me know if there's still a problem and I'll reopen — this could be a browserify bug that got fixed.
