### ISSUE TITLE
[Edge browser] With URL.revokeObjectURL no message is received in the worker

### ISSUE THREAD

**Issue by cnsdato** [substack/webworkify#26]
V1.2.1 no longer working in Edge browser.
V1.2.0 works fine.

**Comment by anandthakker** [comment]
@cnsdato Thanks for the report.  I guess maybe Edge is loading the worker source asynchronously?  Not exactly sure.  Ways we could deal with this:
 - Since there's now an options param, the `revokeObjectURL` behavior could be controlled by an option.
 - Since `bare: true` lets you do the object URL creation and Worker construction yourself, we could just remove the `revokeObjectURL` stuff from here, recommending instead that, where needed, people can do it themselves more safely by waiting until they've heard back from their worker before revoking.
 - We could stick a `releaseURL` function onto the `worker` before returning it, so that people can decide when to release the url without having to use the `bare: true` version of the api.

@substack preferences?

**Comment by anandthakker** [comment]
Going with (IMO) the simplest approach, which is to just attach `objectURL` to the returned worker so that user code can decide if/when to revoke it.

**Comment by anandthakker** [comment]
@cnsdato Just pushed what I believe should be a fix for this and published as 1.3.0.  It would be great if you could confirm?

**Comment by cnsdato** [comment]
@anandthakker Thanks for fixing this, I will give it a try in the next few days and will give you response on this.

**Comment by mourner** [comment]
This was fixed.
